# Generated by Django 4.2.11 on 2025-10-15 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
