# Generated by Django 4.2.11 on 2025-10-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_register_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password_confirm',
        ),
    ]
