# Generated by Django 4.2.11 on 2025-10-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_register_password_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='utilisateur_defaut', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
